# Python Fundamentals Summary

## Goal

Demonstrate deterministic Python, NumPy, and pandas operations and show how small reusable utilities support the SPY volatility-risk project.

## Setup

Run safely from either `project/` or `project/notebooks/`.

In [1]:
from pathlib import Path
import os, sys

if Path.cwd().name == 'notebooks':
    os.chdir('..')
ROOT = Path.cwd()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
print('working from:', ROOT.name)

working from: project

## Steps

### 1. Python and NumPy

In [2]:
import numpy as np

prices = [100.0, 101.0, 103.0]
price_array = np.array(prices)
simple_returns = price_array[1:] / price_array[:-1] - 1
print('Python prices:', prices)
print('NumPy simple returns:', np.round(simple_returns, 6))

Python prices: [100.0, 101.0, 103.0]
NumPy simple returns: [0.01     0.019802]

### 2. pandas

In [3]:
import pandas as pd

price_frame = pd.DataFrame({
    'Trade Date': ['2026-01-05', '2026-01-02', '2026-01-06'],
    'Adj Close ($)': [101.0, 100.0, 103.0],
})
price_frame

   Trade Date  Adj Close ($)
0  2026-01-05          101.0
1  2026-01-02          100.0
2  2026-01-06          103.0

### 3. Reusable Utilities

In [4]:
from src.utils import clean_columns, parse_date_column

cleaned = clean_columns(price_frame)
cleaned = parse_date_column(cleaned, 'trade_date')
cleaned

  trade_date  adj_close
0 2026-01-02      100.0
1 2026-01-05      101.0
2 2026-01-06      103.0

## Checks

In [5]:
assert cleaned.columns.tolist() == ['trade_date', 'adj_close']
assert cleaned['trade_date'].is_monotonic_increasing
assert len(cleaned) == 3
assert np.isclose(simple_returns[0], 0.01)
print('All Stage 03 checks passed.')

All Stage 03 checks passed.

## Next Steps

The same column and date utilities will normalize acquired market data before validation, storage, and Stage 06 preprocessing.